/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.29.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as bookings from "../bookings.js";
import type * as events from "../events.js";
import type * as media from "../media.js";
import type * as newsletter from "../newsletter.js";
import type * as seed from "../seed.js";
import type * as tracks from "../tracks.js";

export const api: FilterApi<
  ApiFromModules<{
    bookings: typeof bookings;
    events: typeof events;
    media: typeof media;
    newsletter: typeof newsletter;
    seed: typeof seed;
    tracks: typeof tracks;
  }>,
  FunctionReference<any, "public">
> = {} as any;

export const internal: FilterApi<
  ApiFromModules<{
    bookings: typeof bookings;
    events: typeof events;
    media: typeof media;
    newsletter: typeof newsletter;
    seed: typeof seed;
    tracks: typeof tracks;
  }>,
  FunctionReference<any, "internal">
> = {} as any;
