/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.29.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

export const api: FilterApi<
  ApiFromModules<{}>,
  FunctionReference<any, "public">
>;
export const internal: FilterApi<
  ApiFromModules<{}>,
  FunctionReference<any, "internal">
>;
